/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_defeat.lh
 */
export class GameResultBase extends Laya.Dialog {
    public Text: Laya.Text;
}

