/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_rank.lh
 */
export class GameRankBase extends Laya.Dialog {
    public panel: Laya.Panel;
}

