/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_rankItem.lh
 */
export class GameRankItemBase extends Laya.Box {
    public bg: Laya.Image;
    public rank: Laya.Label;
    public playerid: Laya.Label;
    public score: Laya.Label;
}

