/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Game.ls
 */
export class GameBase extends Laya.Scene {
    public bg: Laya.Image;
    public bottom_frame: Laya.Image;
    public top_frame: Laya.Image;
    public round_label: Laya.Label;
    public score_label: Laya.Label;
    public score_number: Laya.Label;
    public info_label: Laya.Label;
    public view: Laya.Image;
    public Mask: Laya.Image;
    public seed_label: Laya.Label;
    public seed_text: Laya.Label;
}

