/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Home.ls
 */
export class HomeBase extends Laya.Scene {
    public pve_button: Laya.Button;
    public build_button: Laya.Button;
    public pvp_button: Laya.Button;
    public rank_button: Laya.Button;
    public Mask: Laya.Image;
}

