/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Login.ls
 */
export class LoginBase extends Laya.Scene {
    public login_button: Laya.Button;
}

